### ISSUE TITLE
Move field weeks_in_advance from Store to PickupDateSeries

### ISSUE THREAD

**Issue by mr-kojo** [yunity/karrot-backend#451]
Move the field `weeks_in_advance` from the `Store` model to the `PickupDateSeries` model.

Actually, it would be sufficient if this setting is only adjustable once per store instead of once per series. However, from a code design perspective, the setting is more of an attribute of a series than of a store: Every series needs to know this setting, but a store may not necessarily go along with a series (if it has only one-time pickups, or none at all). So moving this setting to `PickupDateSeries` is in favour of a clean backend with less coupling.

Steps:
- [ ] Migrate the field, adapt references
- [ ] [Migrate corresponding data](https://docs.djangoproject.com/en/1.11/topics/migrations/#data-migrations)
- [ ] Write a migration test (see [here](https://github.com/yunity/karrot-backend/pull/450/commits/095744395f127a9725c986c5e12d75329119b8c2))
- [ ] Warn frontend developers that the API will change

**Comment by nicksellen** [comment]
If the user requirement were to set it on the store (for whatever reason), then the coupling is at the user domain level and I don't see the problem in representing a user domain coupling in the code (as the code is to represent the user domain).

In this case though I'm not aware of a user requirement for either approach, and I can _imagine_ scenarios in which either would make sense.

So, I disagree that it's a code design question, but I also have no strong resistance to changing it in the user domain.

Although it's usually best to have a clear user requirement before implementing something that changes something user facing, partly in order to avoid discussions like this, but also to make sure we don't make incorrect assumptions about user requirements (developers are quite commonly terrible at understanding user needs).

**Comment by mr-kojo** [comment]
Fair enough, let's leave it as it is for now, then.
